services:
  - type: web
    name: mini-crm-backend
    runtime: node
    plan: free
    buildCommand: cd mini-crm && npm run install-server
    startCommand: cd mini-crm && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_DIALECT
        value: mysql
      - key: DB_HOST
        value: sql12.freesqldatabase.com
      - key: DB_USER
        value: sql12821844
      - key: DB_PASSWORD
        value: kabucxkbIu
      - key: DB_NAME
        value: sql12821844
      - key: JWT_SECRET
        generateValue: true
